# Generated by Django 3.2.1 on 2021-07-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_alter_machinedata_total_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedata',
            name='total_minutes',
            field=models.FloatField(default=5),
        ),
    ]
